#!/usr/bin/env bash
file=$1
extension="${file##*.}"

run_git_blame() {
	if [ -n "$FZF_DIFF_PREVIEW_CMD" ]; then
		git blame "$file" | $FZF_DIFF_PREVIEW_CMD --default-language "$extension"
	else
		git blame --abbrev=8 "$file"
	fi
}

# Check if the file command is available
if command -v file >/dev/null 2>&1; then
	# Check if the file is binary or an image
	if file --mime-type "$file" | grep -qE 'application/octet-stream|image/'; then
		"$FZF_PREVIEW_CMD" "$file"
	else
		run_git_blame
	fi
else
	# Default to the current else command if file command is not available
	run_git_blame
fi
