#!/usr/bin/env bash

target_name=$1

packages=$(rg --no-heading -N --glob 'package.json' '"name"' 2>/dev/null | sed -E 's|(.*):.*"name": *"([^"]+)".*|{"name":"\2","path":"\1"}|' | jq -s .)
crates=$(fd -a Cargo.toml -x sh -c '
		name=$(grep -m1 "^name" "$1" | sed -E "s/name *= *\"([^\"]+)\"/\1/")
		[ -n "$name" ] && echo "{\"name\":\"$name\",\"path\":\"$1\"}"
	' _ {} | jq -s .)

locations=$(echo "$packages" "$crates" | jq -s ".[0] + .[1] | .[] | select(.name == \"$target_name\") | .path" -r)

if [ "$(echo "$locations" | wc -l)" -gt 1 ]; then
	printf "\033[33mWarning: More than one location found for %s\033[0m\n" "$target_name"
fi

while IFS= read -r location; do
	echo "$location"
	$FZF_PREVIEW_CMD "$location"
done <<< "$locations"
