#!/usr/bin/env zsh

commit=$1
if [ -n "$FZF_DIFF_PREVIEW_CMD" ]; then
	git show --color=always --stat --patch "$commit" | $FZF_DIFF_PREVIEW_CMD
else
	git show --color=always --stat --patch "$commit"
fi
