#!/usr/bin/env bash

commit_hash=${1//^/}
# Check if FZF_DIFF_PREVIEW_CMD is set
if [ -n "$FZF_DIFF_PREVIEW_CMD" ]; then
    git show "$commit_hash" | $FZF_DIFF_PREVIEW_CMD
else
    git show "$commit_hash"
fi