#!/usr/bin/env zsh

status_line="$1"
staged_status="${status_line[1]}"
unstaged_status="${status_line[2]}"
file="${status_line[4,-1]}"
if [ -n "$FZF_DIFF_PREVIEW_CMD" ]; then
	if [[ "$staged_status" == "M" ]]; then
		echo 'Staged changes:'
		git diff --color=always --cached "$file" | $FZF_DIFF_PREVIEW_CMD
	fi
	if [[ "$unstaged_status" == "M" ]]; then
		echo 'Unstaged changes:'
		git diff --color=always "$file" | $FZF_DIFF_PREVIEW_CMD
	fi
	if [[ "$staged_status" == "?" && "$unstaged_status" == "?" ]]; then
		"$FZF_PREVIEW_CMD" "$file"
	fi
else
	if [[ "$staged_status" == "M" ]]; then
		echo 'Staged changes:'
		git diff --color=always --cached "$file"
	fi
	if [[ "$unstaged_status" == "M" ]]; then
		echo 'Unstaged changes:'
		git diff --color=always "$file"
	fi
	if [[ "$staged_status" == "?" && "$unstaged_status" == "?" ]]; then
		echo 'Untracked:'
		"$FZF_PREVIEW_CMD" "$file"
	fi
fi
