#!/usr/bin/env bash

target_name=$1
cache_file=$2

locations=$(jq -r ".[] | select(.name == \"$target_name\") | .path" "$cache_file")

if [ "$(echo "$locations" | wc -l)" -gt 1 ]; then
  printf "\033[33mWarning: More than one location found for %s\033[0m\n" "$target_name"
fi

for location in $locations; do
  echo "$location"
  $FZF_PREVIEW_CMD "$location"
done